// <auto-generated />
using System;
using Mathy.ELM.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mathy.ELM.Infrastructure.Migrations
{
    [DbContext(typeof(MathyELMContext))]
    [Migration("20260304000000_AddUseExistingKeyFobToNewHireRequestDetails")]
    partial class AddUseExistingKeyFobToNewHireRequestDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
